# Generated by Django 4.2.16 on 2024-11-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
