# Generated by Django 4.2.16 on 2024-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
