# Generated by Django 4.2.16 on 2024-11-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_form_is_published_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
