# Generated by Django 4.2.16 on 2024-11-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_alter_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='rating.form'),
            preserve_default=False,
        ),
    ]
