# Generated by Django 4.2.16 on 2024-11-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_answer_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form', to='rating.form'),
        ),
    ]
