# Generated by Django 4.2.16 on 2024-11-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0009_alter_answer_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form', to='rating.form'),
        ),
    ]
